### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Crear una vista SQL

In [0]:
from pyspark.sql.functions import *

estudiante = [(1,"Alfonso","Science",86,"A",90),
              (1,"Alfonso","Science",86,"A",90),
              (2,"Maria","Math",56,"R",55),
              (3,"Javiera","English",77,"A",85),
              (3,"Javiera","English",77,"A",85),
              (4,"Andres","Science",89,"A",98),
              (5,"Tomas","Math",69,"A",70),
              (5,"Tomas","Math",69,"A",70),
              (6,"Raul",'Phisics',45,"R",50),
              (7,"Pedro","English",61,"A",70)
             ]
schema = ["id","nombre","ramo","puntaje","status","asistencia"]

df = spark.createDataFrame(data=estudiante, schema=schema)
df.printSchema()
df.show()

root
 |-- id: long (nullable = true)
 |-- nombre: string (nullable = true)
 |-- ramo: string (nullable = true)
 |-- puntaje: long (nullable = true)
 |-- status: string (nullable = true)
 |-- asistencia: long (nullable = true)

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+

#### Crear una vista SQL --> Local Temp View
Solo se puede utilizar el notebook donde se creó

##### Forma 1

In [0]:
df.createOrReplaceTempView("df")

In [0]:
df2 = spark.sql("SELECT * FROM df WHERE asistencia > 85")

In [0]:
df2.show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  1|Alfonso|Science|     86|     A|        90|
|  4| Andres|Science|     89|     A|        98|
+---+-------+-------+-------+------+----------+

##### Forma 2

In [0]:
df.createOrReplaceTempView("df")

In [0]:
asistencia_cant = 85

In [0]:
df3 = spark.sql(f"SELECT * FROM df WHERE asistencia > {asistencia_cant}")

In [0]:
df3.show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  1|Alfonso|Science|     86|     A|        90|
|  4| Andres|Science|     89|     A|        98|
+---+-------+-------+-------+------+----------+

##### Forma 3

In [0]:
df.createOrReplaceTempView("df")

In [0]:
%sql
SELECT *
FROM df
WHERE asistencia > 85

id,nombre,ramo,puntaje,status,asistencia
1,Alfonso,Science,86,A,90
1,Alfonso,Science,86,A,90
4,Andres,Science,89,A,98

#### Crear una vista SQL --> Global Temp View
Se puede utilizar en todos los notebooks que estén conectados al mismo cluster donde se creó

In [0]:
df.createOrReplaceGlobalTempView("df_global")

In [0]:
%sql
SHOW TABLES

database,tableName,isTemporary
,df,true

In [0]:
%sql
SHOW TABLES IN global_temp

database,tableName,isTemporary
global_temp,df_global,true
,df,true

In [0]:
%sql
SELECT *
  FROM global_temp.df_global;

id,nombre,ramo,puntaje,status,asistencia
1,Alfonso,Science,86,A,90
1,Alfonso,Science,86,A,90
2,Maria,Math,56,R,55
3,Javiera,English,77,A,85
3,Javiera,English,77,A,85
4,Andres,Science,89,A,98
5,Tomas,Math,69,A,70
5,Tomas,Math,69,A,70
6,Raul,Phisics,45,R,50
7,Pedro,English,61,A,70

In [0]:
spark.sql("SELECT * \
  FROM global_temp.df_global").show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+