### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Creaci√≥n de Dataframes con una columna map

#### Forma 1

In [0]:
map_brand = [
        ('Raja',{'TV':'LG','Refrigerator':'Samsung','Oven':'Phillips','AC':'Voltas'}),
        ('Raghav',{'AC':'Samsung','Washing machine':'LG'}),
        ('Ram',{'Grinder':'Preethi','TV':''}),
        ('Ramesh',{'Refrigerator':'LG','TV':'Croma'}),
        ('Rajesh',None)]

df = spark.createDataFrame(data=map_brand, schema = ['name','brand'])
df.printSchema()
display(df)

root
 |-- name: string (nullable = true)
 |-- brand: map (nullable = true)
 |    |-- key: string
 |    |-- value: string (valueContainsNull = true)

name,brand
Raja,"Map(Refrigerator -> Samsung, AC -> Voltas, TV -> LG, Oven -> Phillips)"
Raghav,"Map(AC -> Samsung, Washing machine -> LG)"
Ram,"Map(TV -> , Grinder -> Preethi)"
Ramesh,"Map(Refrigerator -> LG, TV -> Croma)"
Rajesh,null

#### Forma 2

In [0]:
from pyspark.sql.functions import element_at, lit

array = [({"a":1.0, "b":2.0},), ({"c":3.0, "d":4.0},)]

df = spark.createDataFrame(data=array, schema=['data'])
df.printSchema()
df.show()

root
 |-- data: map (nullable = true)
 |    |-- key: string
 |    |-- value: double (valueContainsNull = true)

+--------------------+
|                data|
+--------------------+
|{a -> 1.0, b -> 2.0}|
|{d -> 4.0, c -> 3.0}|
+--------------------+

#### Forma 3

In [0]:
from pyspark.sql.functions import element_at, lit

df = spark.createDataFrame([({"a":1.0, "b":2.0},), ({"c":3.0, "d":4.0},)], ['data'])
df.printSchema()
df.show()

root
 |-- data: map (nullable = true)
 |    |-- key: string
 |    |-- value: double (valueContainsNull = true)

+--------------------+
|                data|
+--------------------+
|{a -> 1.0, b -> 2.0}|
|{d -> 4.0, c -> 3.0}|
+--------------------+