### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Creaci√≥n de Dataframes con una lista de valores

#### Utilizando una lista de strings

In [0]:
from pyspark.sql.types import StringType

auto = ['toyota','mazda','tesla','audi','ferrari']

df = spark.createDataFrame(auto, StringType()).withColumnRenamed('value','marca')
# df = spark.createDataFrame(auto, 'string')

df.printSchema()
df.show()

root
 |-- marca: string (nullable = true)

+-------+
|  marca|
+-------+
| toyota|
|  mazda|
|  tesla|
|   audi|
|ferrari|
+-------+

#### Utilizando una lista de enteros

In [0]:
from pyspark.sql.types import IntegerType

numero = [1,2,3,4,5,6]

df = spark.createDataFrame(numero, IntegerType()).withColumnRenamed('value','numero')
# df = spark.createDataFrame(auto, 'string')

df.printSchema()
df.show()

root
 |-- numero: integer (nullable = true)

+------+
|numero|
+------+
|     1|
|     2|
|     3|
|     4|
|     5|
|     6|
+------+

#### Utilizando una lista de tuplas

In [0]:
tupla = [(10,'diez'),(20,'veinte'),(30,'treinta')]

df = spark.createDataFrame(tupla, 'id int, nombre string')

df.printSchema()
df.show()

root
 |-- id: integer (nullable = true)
 |-- nombre: string (nullable = true)

+---+-------+
| id| nombre|
+---+-------+
| 10|   diez|
| 20| veinte|
| 30|treinta|
+---+-------+