### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Eliminar columnas

In [0]:
from pyspark.sql.functions import lit, concat, col

employee_data = [(10,"Raj","Kumar","1999","100","M",2000),
                 (20,"Rahul","Rajan","2002","200","f",2000),
                 (30,"Raghav","Manish","2010","100",None,2000),
                 (40,"Raja","Singh","2004","100","F",2000),
                 (50,"Rama","Krish","2008","400","M",2000),
                 (60,"Rasul","Kutty","2014","500","M",2000),
                 (70,"Kumar","Chand","2004","600","M",2000)
                ]
employee_schema = ["employee_id","first_name","last_name","doj",
                   "employee_dept_id","gender","salary"]

df = spark.createDataFrame(data=employee_data, schema=employee_schema)

#### Eliminar una columna

##### Forma 1

In [0]:
df_modif = df.drop('salary')

display(df_modif)

employee_id,first_name,last_name,doj,employee_dept_id,gender
10,Raj,Kumar,1999,100,M
20,Rahul,Rajan,2002,200,f
30,Raghav,Manish,2010,100,null
40,Raja,Singh,2004,100,F
50,Rama,Krish,2008,400,M
60,Rasul,Kutty,2014,500,M
70,Kumar,Chand,2004,600,M

##### Forma 2

In [0]:
df_modif = df.drop(col('salary'))

display(df_modif)

employee_id,first_name,last_name,doj,employee_dept_id,gender
10,Raj,Kumar,1999,100,M
20,Rahul,Rajan,2002,200,f
30,Raghav,Manish,2010,100,null
40,Raja,Singh,2004,100,F
50,Rama,Krish,2008,400,M
60,Rasul,Kutty,2014,500,M
70,Kumar,Chand,2004,600,M

##### Forma 3

In [0]:
df_modif = df.drop(df['salary'])

display(df_modif)

employee_id,first_name,last_name,doj,employee_dept_id,gender
10,Raj,Kumar,1999,100,M
20,Rahul,Rajan,2002,200,f
30,Raghav,Manish,2010,100,null
40,Raja,Singh,2004,100,F
50,Rama,Krish,2008,400,M
60,Rasul,Kutty,2014,500,M
70,Kumar,Chand,2004,600,M

#### Eliminar m√∫ltiples columnas

##### Forma 1

In [0]:
df_modif = df.drop('gender').drop('salary')

display(df_modif)

employee_id,first_name,last_name,doj,employee_dept_id
10,Raj,Kumar,1999,100
20,Rahul,Rajan,2002,200
30,Raghav,Manish,2010,100
40,Raja,Singh,2004,100
50,Rama,Krish,2008,400
60,Rasul,Kutty,2014,500
70,Kumar,Chand,2004,600

##### Forma 2

In [0]:
df_modif = df.drop('gender','salary')

display(df_modif)

employee_id,first_name,last_name,doj,employee_dept_id
10,Raj,Kumar,1999,100
20,Rahul,Rajan,2002,200
30,Raghav,Manish,2010,100
40,Raja,Singh,2004,100
50,Rama,Krish,2008,400
60,Rasul,Kutty,2014,500
70,Kumar,Chand,2004,600

#### Error al utilizar .col para eliminar m√∫ltiples columnas

In [0]:
df_modif = df.drop(col('gender'),col('salary'))

display(df_modif)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-804623631765890> in <cell line: 1>()
----> 1 df_modif = df.drop(col('gender'),col('salary'))
      2
      3 display(df_modif)

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/dataframe.py in drop(self, *cols)
   3419             for col in cols:
   3420                 if not isinstance(col, str):
-> 3421                     raise TypeError("each col in the param list should be a string")
   3422             jdf = self._jdf.drop(self._jseq(cols))
   3423

TypeError: each col in the param list should be a string

#### Si tenemos un nombre de columna que no existe, la columna ser√° ignorada

In [0]:
df_modif = df.drop('gender','salary','location')

display(df_modif)

employee_id,first_name,last_name,doj,employee_dept_id
10,Raj,Kumar,1999,100
20,Rahul,Rajan,2002,200
30,Raghav,Manish,2010,100
40,Raja,Singh,2004,100
50,Rama,Krish,2008,400
60,Rasul,Kutty,2014,500
70,Kumar,Chand,2004,600

#### Eliminar una lista de columnas

In [0]:
lista = ['doj','gender','salary']

df_modif = df.drop(*lista)

df_modif.show()

+-----------+----------+---------+----------------+
|employee_id|first_name|last_name|employee_dept_id|
+-----------+----------+---------+----------------+
|         10|       Raj|    Kumar|             100|
|         20|     Rahul|    Rajan|             200|
|         30|    Raghav|   Manish|             100|
|         40|      Raja|    Singh|             100|
|         50|      Rama|    Krish|             400|
|         60|     Rasul|    Kutty|             500|
|         70|     Kumar|    Chand|             600|
+-----------+----------+---------+----------------+