### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Extraer una subcadena utilizando una expresión regular

In [0]:
from pyspark.sql.functions import col, regexp_extract

data = [(1,'nombre A','Gibson'),
        (2,'nombre B','Fender'),
        (3,'nombre C','Ibanez')
       ]

df = spark.createDataFrame(data).toDF('id','nombre','empresa')
df.printSchema()
df.show(truncate=False)

root
 |-- id: long (nullable = true)
 |-- nombre: string (nullable = true)
 |-- empresa: string (nullable = true)

+---+--------+-------+
|id |nombre  |empresa|
+---+--------+-------+
|1  |nombre A|Gibson |
|2  |nombre B|Fender |
|3  |nombre C|Ibanez |
+---+--------+-------+

#### regexp_extract

El método regexp_extract extrae una subcadena utilizando una expresión regular.

In [0]:
extract = '(A|C)'

df_nuevo = df.select(regexp_extract(col('nombre'),extract,1).alias('extraido'),col('nombre'))

df_nuevo.show()

+--------+--------+
|extraido|  nombre|
+--------+--------+
|       A|nombre A|
|        |nombre B|
|       C|nombre C|
+--------+--------+