### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Cambiar a un tipo de dato unico para todas las columnas

In [0]:
from pyspark.sql.functions import *
from pyspark.sql.types import *

estudiante = [("Alfonso","Science",86,"A",90),
              ("Maria","Math",56,"R",None),
              ("Javiera","English",77,"A",85),
              ("Andres","Science",None,"A",None),
              ("Tomas","Math",69,"A",70),
              ("Raul",None,45,"R",50),
              ("Pedro","English",None,None,55)
             ]
schema = ["nombre","ramo","puntaje","status","asistencia"]

df.printSchema()
df = spark.createDataFrame(data=estudiante, schema=schema)
df.show()

root
 |-- nombre: string (nullable = true)
 |-- ramo: string (nullable = true)
 |-- puntaje: long (nullable = true)
 |-- status: string (nullable = true)
 |-- asistencia: long (nullable = true)

+-------+-------+-------+------+----------+
| nombre|   ramo|puntaje|status|asistencia|
+-------+-------+-------+------+----------+
|Alfonso|Science|     86|     A|        90|
|  Maria|   Math|     56|     R|      null|
|Javiera|English|     77|     A|        85|
| Andres|Science|   null|     A|      null|
|  Tomas|   Math|     69|     A|        70|
|   Raul|   null|     45|     R|        50|
|  Pedro|English|   null|  null|        55|
+-------+-------+-------+------+----------+

In [0]:
schema_modif = df.select([col(c).cast(StringType()).alias(c) for c in df.columns])
schema_modif.printSchema()
schema_modif.show()

root
 |-- nombre: string (nullable = true)
 |-- ramo: string (nullable = true)
 |-- puntaje: string (nullable = true)
 |-- status: string (nullable = true)
 |-- asistencia: string (nullable = true)

+-------+-------+-------+------+----------+
| nombre|   ramo|puntaje|status|asistencia|
+-------+-------+-------+------+----------+
|Alfonso|Science|     86|     A|        90|
|  Maria|   Math|     56|     R|      null|
|Javiera|English|     77|     A|        85|
| Andres|Science|   null|     A|      null|
|  Tomas|   Math|     69|     A|        70|
|   Raul|   null|     45|     R|        50|
|  Pedro|English|   null|  null|        55|
+-------+-------+-------+------+----------+