### ![Spark Logo Tiny](https://files.training.databricks.com/images/105/logo_spark_tiny.png) Eliminar registros duplicados

**distinct( )** , **dropDuplicates( )** y **drop_duplicates()** cumplen la misma funci√≥n.

In [0]:
from pyspark.sql.functions import *

estudiante = [(1,"Alfonso","Science",86,"A",90),
              (1,"Alfonso","Science",86,"A",90),
              (2,"Maria","Math",56,"R",55),
              (3,"Javiera","English",77,"A",85),
              (3,"Javiera","English",77,"A",85),
              (4,"Andres","Science",89,"A",98),
              (5,"Tomas","Math",69,"A",70),
              (5,"Tomas","Math",69,"A",70),
              (6,"Raul",'Phisics',45,"R",50),
              (7,"Pedro","English",61,"A",70)
             ]
schema = ["id","nombre","ramo","puntaje","status","asistencia"]

df = spark.createDataFrame(data=estudiante, schema=schema)
df.printSchema()
df.show()

root
 |-- id: long (nullable = true)
 |-- nombre: string (nullable = true)
 |-- ramo: string (nullable = true)
 |-- puntaje: long (nullable = true)
 |-- status: string (nullable = true)
 |-- asistencia: long (nullable = true)

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+

#### dropDuplicates()

In [0]:
df.dropDuplicates().show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  7|  Pedro|English|     61|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
+---+-------+-------+-------+------+----------+

#### drop_duplicates()

In [0]:
df.drop_duplicates().show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  7|  Pedro|English|     61|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
+---+-------+-------+-------+------+----------+

In [0]:
df.drop_duplicates(subset=None).show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  7|  Pedro|English|     61|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
+---+-------+-------+-------+------+----------+

#### distinct()

In [0]:
df.distinct().show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  7|  Pedro|English|     61|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
+---+-------+-------+-------+------+----------+

#### Eliminar duplicados basado en una columna(s) especifica(s)

In [0]:
df.dropDuplicates('id').show()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-348697247138785> in <cell line: 1>()
----> 1 df.dropDuplicates('id').show()

/databricks/spark/python/pyspark/instrumentation_utils.py in wrapper(*args, **kwargs)
     46             start = time.perf_counter()
     47             try:
---> 48                 res = func(*args, **kwargs)
     49                 logger.log_success(
     50                     module_name, class_name, function_name, time.perf_counter() - start, signature

/databricks/spark/python/pyspark/sql/dataframe.py in dropDuplicates(self, subset)
   2687         """
   2688         if subset is not None and (not isinstance(subset, Iterable) or isinstance(subset, str)):
-> 2689             raise TypeError("Parameter 'subset' must be a list of columns")
   2690
   2691         if subset is None:

TypeError: Parameter 'subset' must be a list of columns

In [0]:
df.dropDuplicates(['id']).show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+

In [0]:
df.dropDuplicates(subset = ['id']).show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+

In [0]:
df.dropDuplicates(['id','ramo']).show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+

In [0]:
df.drop_duplicates(['id','ramo']).show()

+---+-------+-------+-------+------+----------+
| id| nombre|   ramo|puntaje|status|asistencia|
+---+-------+-------+-------+------+----------+
|  1|Alfonso|Science|     86|     A|        90|
|  2|  Maria|   Math|     56|     R|        55|
|  3|Javiera|English|     77|     A|        85|
|  4| Andres|Science|     89|     A|        98|
|  5|  Tomas|   Math|     69|     A|        70|
|  6|   Raul|Phisics|     45|     R|        50|
|  7|  Pedro|English|     61|     A|        70|
+---+-------+-------+-------+------+----------+